/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as BootstrapRouteImport } from './routes/bootstrap'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PQrTokenRouteImport } from './routes/p.$qrToken'
import { Route as AppUsersRouteImport } from './routes/_app.users'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppScanRouteImport } from './routes/_app.scan'
import { Route as AppReportsRouteImport } from './routes/_app.reports'
import { Route as AppQuickAddRouteImport } from './routes/_app.quick-add'
import { Route as AppParticipantsRouteImport } from './routes/_app.participants'
import { Route as AppImportRouteImport } from './routes/_app.import'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppBadgesRouteImport } from './routes/_app.badges'
import { Route as AppAlertsRouteImport } from './routes/_app.alerts'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const BootstrapRoute = BootstrapRouteImport.update({
  id: '/bootstrap',
  path: '/bootstrap',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PQrTokenRoute = PQrTokenRouteImport.update({
  id: '/p/$qrToken',
  path: '/p/$qrToken',
  getParentRoute: () => rootRouteImport,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppScanRoute = AppScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppQuickAddRoute = AppQuickAddRouteImport.update({
  id: '/quick-add',
  path: '/quick-add',
  getParentRoute: () => AppRoute,
} as any)
const AppParticipantsRoute = AppParticipantsRouteImport.update({
  id: '/participants',
  path: '/participants',
  getParentRoute: () => AppRoute,
} as any)
const AppImportRoute = AppImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppBadgesRoute = AppBadgesRouteImport.update({
  id: '/badges',
  path: '/badges',
  getParentRoute: () => AppRoute,
} as any)
const AppAlertsRoute = AppAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bootstrap': typeof BootstrapRoute
  '/login': typeof LoginRoute
  '/alerts': typeof AppAlertsRoute
  '/badges': typeof AppBadgesRoute
  '/dashboard': typeof AppDashboardRoute
  '/import': typeof AppImportRoute
  '/participants': typeof AppParticipantsRoute
  '/quick-add': typeof AppQuickAddRoute
  '/reports': typeof AppReportsRoute
  '/scan': typeof AppScanRoute
  '/settings': typeof AppSettingsRoute
  '/users': typeof AppUsersRoute
  '/p/$qrToken': typeof PQrTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bootstrap': typeof BootstrapRoute
  '/login': typeof LoginRoute
  '/alerts': typeof AppAlertsRoute
  '/badges': typeof AppBadgesRoute
  '/dashboard': typeof AppDashboardRoute
  '/import': typeof AppImportRoute
  '/participants': typeof AppParticipantsRoute
  '/quick-add': typeof AppQuickAddRoute
  '/reports': typeof AppReportsRoute
  '/scan': typeof AppScanRoute
  '/settings': typeof AppSettingsRoute
  '/users': typeof AppUsersRoute
  '/p/$qrToken': typeof PQrTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/bootstrap': typeof BootstrapRoute
  '/login': typeof LoginRoute
  '/_app/alerts': typeof AppAlertsRoute
  '/_app/badges': typeof AppBadgesRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/import': typeof AppImportRoute
  '/_app/participants': typeof AppParticipantsRoute
  '/_app/quick-add': typeof AppQuickAddRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/scan': typeof AppScanRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/users': typeof AppUsersRoute
  '/p/$qrToken': typeof PQrTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bootstrap'
    | '/login'
    | '/alerts'
    | '/badges'
    | '/dashboard'
    | '/import'
    | '/participants'
    | '/quick-add'
    | '/reports'
    | '/scan'
    | '/settings'
    | '/users'
    | '/p/$qrToken'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bootstrap'
    | '/login'
    | '/alerts'
    | '/badges'
    | '/dashboard'
    | '/import'
    | '/participants'
    | '/quick-add'
    | '/reports'
    | '/scan'
    | '/settings'
    | '/users'
    | '/p/$qrToken'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/bootstrap'
    | '/login'
    | '/_app/alerts'
    | '/_app/badges'
    | '/_app/dashboard'
    | '/_app/import'
    | '/_app/participants'
    | '/_app/quick-add'
    | '/_app/reports'
    | '/_app/scan'
    | '/_app/settings'
    | '/_app/users'
    | '/p/$qrToken'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  BootstrapRoute: typeof BootstrapRoute
  LoginRoute: typeof LoginRoute
  PQrTokenRoute: typeof PQrTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bootstrap': {
      id: '/bootstrap'
      path: '/bootstrap'
      fullPath: '/bootstrap'
      preLoaderRoute: typeof BootstrapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$qrToken': {
      id: '/p/$qrToken'
      path: '/p/$qrToken'
      fullPath: '/p/$qrToken'
      preLoaderRoute: typeof PQrTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/users': {
      id: '/_app/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/scan': {
      id: '/_app/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof AppScanRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/quick-add': {
      id: '/_app/quick-add'
      path: '/quick-add'
      fullPath: '/quick-add'
      preLoaderRoute: typeof AppQuickAddRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/participants': {
      id: '/_app/participants'
      path: '/participants'
      fullPath: '/participants'
      preLoaderRoute: typeof AppParticipantsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/import': {
      id: '/_app/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof AppImportRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/badges': {
      id: '/_app/badges'
      path: '/badges'
      fullPath: '/badges'
      preLoaderRoute: typeof AppBadgesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/alerts': {
      id: '/_app/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AppAlertsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAlertsRoute: typeof AppAlertsRoute
  AppBadgesRoute: typeof AppBadgesRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppImportRoute: typeof AppImportRoute
  AppParticipantsRoute: typeof AppParticipantsRoute
  AppQuickAddRoute: typeof AppQuickAddRoute
  AppReportsRoute: typeof AppReportsRoute
  AppScanRoute: typeof AppScanRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppUsersRoute: typeof AppUsersRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAlertsRoute: AppAlertsRoute,
  AppBadgesRoute: AppBadgesRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppImportRoute: AppImportRoute,
  AppParticipantsRoute: AppParticipantsRoute,
  AppQuickAddRoute: AppQuickAddRoute,
  AppReportsRoute: AppReportsRoute,
  AppScanRoute: AppScanRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppUsersRoute: AppUsersRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  BootstrapRoute: BootstrapRoute,
  LoginRoute: LoginRoute,
  PQrTokenRoute: PQrTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
